/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const About: string;
declare const cardsList: string;

declare const __default_export__: {
	About: typeof About;
	cardsList: typeof cardsList;
};
export default __default_export__;
