/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const Home: string;

declare const __default_export__: {
	Home: typeof Home;
};
export default __default_export__;
