/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const Card: string;

declare const __default_export__: {
	Card: typeof Card;
};
export default __default_export__;
