/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

const Navbar: string;
const navMain: string;
const navExtension: string;
const show: string;

export default {
	Navbar,
	navMain,
	navExtension,
	show
};
