/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const Navbar: string;
declare const navMain: string;
declare const navExtension: string;
declare const show: string;

declare const __default_export__: {
	Navbar: typeof Navbar;
	navMain: typeof navMain;
	navExtension: typeof navExtension;
	show: typeof show;
};
export default __default_export__;
