/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const main: string;
declare const bottom: string;

declare const __default_export__: {
	main: typeof main;
	bottom: typeof bottom;
};
export default __default_export__;
