/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
/**
 * Generated by vite-css-modules
 * https://npmjs.com/vite-css-modules
 */

declare const NotFound: string;

declare const __default_export__: {
	NotFound: typeof NotFound;
};
export default __default_export__;
